name: Build

on: push

jobs:
  build:
    name: Build for ${{ matrix.display_name }}
    strategy:
      matrix:
        include:
          - display_name: Windows (x86)
            os: windows-2019
            family: windows
            arch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/newton-blockchain/ton.git
          cd ton
          git submodule update --init
          mkdir build

      - name: Configure Windows
        if: ${{ matrix.family == 'windows' }}
        working-directory: ton/build
        env:
          CC: clang
          CXX: clang++
        run: |
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -Wno-dev

      - name: Build
        working-directory: ton/build
        run: |
          cmake --build . \
            -t tonlibjson

      - name: Pack
        working-directory: ton/build
        run: |
          mkdir ../../artifacts && \
          mv crypto/fift ../../artifacts/fift-${{ matrix.family }}-${{ matrix.arch }} && \
          mv crypto/func ../../artifacts/func-${{ matrix.family }}-${{ matrix.arch }} && \
          mv lite-client/lite-client ../../artifacts/lite-client-${{ matrix.family }}-${{ matrix.arch }} && \
          mv rldp-http-proxy/rldp-http-proxy ../../artifacts/rldp-http-proxy-${{ matrix.family }}-${{ matrix.arch }} && \
          cp ../crypto/fift/lib/Asm.fif ../../artifacts/Asm.fif

      - name: Pack (Windows)
        if: ${{ matrix.family == 'windows' }}
        working-directory: ton/build
        run: |
          find tonlib
          mv tonlib/libtonlibjson.0.5.dll ../../artifacts/libtonlibjson-${{ matrix.family }}-${{ matrix.arch }}.dll

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ton-${{ matrix.family }}-${{ matrix.arch }}
          path: artifacts/*
          retention-days: 1

  # release:
  #   name: Create Release
  #   runs-on: ubuntu-20.04
  #   needs: build
  #   if: github.ref_type == 'tag'
  #   steps:
  #     - name: Create directory for artifacts
  #       run: mkdir artifacts

  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         path: artifacts

  #     - name: Create Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: "artifacts/ton-linux-amd64/*,artifacts/ton-darwin-amd64/*"
  #         token: ${{ secrets.GITHUB_TOKEN }}
